name: meenavar_thunai
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Google Services
  google_sign_in: ^6.1.4
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.0
  google_generative_ai: ^0.4.3

  # Location
  location: ^8.0.0
  geolocator: ^13.0.3
  flutter_map_geojson: ^1.0.8

  # Local Storage
  shared_preferences: ^2.5.2

  # UI Components
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  
  # Utils
  http: ^1.4.0
  get_it: ^8.0.3
  intl: ^0.20.2
  uuid: ^4.5.1
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  vibration: ^3.1.3
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/india_eez.geojson

