// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ws10me6nrLs0fQGPJAwd2_M-8KSJqPE',
    appId: '1:183498713374:web:ee9478fbc7f766a062410f',
    messagingSenderId: '183498713374',
    projectId: 'sol-challenge',
    authDomain: 'sol-challenge.firebaseapp.com',
    storageBucket: 'sol-challenge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6V8LHB9vQ7RMS8nhE7gZ38SIgFu_JuZ8',
    appId: '1:183498713374:android:ec58e95ab9a30b0a62410f',
    messagingSenderId: '183498713374',
    projectId: 'sol-challenge',
    storageBucket: 'sol-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6jE9mdjQI-TnlJlqkOK9gBUkSJwksfTM',
    appId: '1:183498713374:ios:6ffc7ae56515276262410f',
    messagingSenderId: '183498713374',
    projectId: 'sol-challenge',
    storageBucket: 'sol-challenge.firebasestorage.app',
    iosBundleId: 'com.example.meenavarThunai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6jE9mdjQI-TnlJlqkOK9gBUkSJwksfTM',
    appId: '1:183498713374:ios:6ffc7ae56515276262410f',
    messagingSenderId: '183498713374',
    projectId: 'sol-challenge',
    storageBucket: 'sol-challenge.firebasestorage.app',
    iosBundleId: 'com.example.meenavarThunai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ws10me6nrLs0fQGPJAwd2_M-8KSJqPE',
    appId: '1:183498713374:web:c7959f4bb5220e9862410f',
    messagingSenderId: '183498713374',
    projectId: 'sol-challenge',
    authDomain: 'sol-challenge.firebaseapp.com',
    storageBucket: 'sol-challenge.firebasestorage.app',
  );
}
